.\" SPDX-FileCopyrightText: The Bio++ Development Group
.\"
.\" SPDX-License-Identifier: CECILL-2.1

.TH BPPALNSCORE 1 LOCAL

.SH NAME

bppalnscore - Bio++ alignment scoring

.SH SYNOPSIS

.B bppalnscore [options]

.SH AVAILABILITY

All UNIX flavors

.SH DESCRIPTION

bppalnscore compares two alignment and compute corresponding column scores.
Scores can be output to a text file, and/or used to generate a site selection
to be output as a Mase file.

.SH OPTIONS

You should refer to 'info bppsuite' or to the online manual of bppsuite for a complete list of available options.

.TP 5

--noninteractive

generates output for redirection in a file.

.TP

param=file

reads a file for loading options

.SH AUTHOR

Bio++ Development Team.
