.\" SPDX-FileCopyrightText: The Bio++ Development Group
.\"
.\" SPDX-License-Identifier: CECILL-2.1

.TH BPPDIST 1 LOCAL

.SH NAME

bppdist - Distance methods for phylogenetic reconstruction with Bio++

.SH SYNOPSIS

.B bppdist [options]

.SH AVAILABILITY

All UNIX flavors

.SH DESCRIPTION

bppdist performs phylogenetic reconstruction using distance methods (like neighbor joining or bioNJ).

.SH OPTIONS

You should refer to 'info bppsuite' or to the online manual of bppsuite for a complete list of available options.

.TP 5

--noninteractive

generates output for redirection in a file.

.TP

param=file

reads a file for loading options

.SH AUTHOR

The Bio++ Development Team.
